### ISSUE TITLE
test

### ISSUE THREAD

**Issue by DaveYesland** [d-l-y/Resources#1]
test

**Comment by d-l-y** [comment]
@daveyesland

**Comment by DaveYesland** [comment]
hi

**Comment by DaveYesland** [comment]
Confirm your email address

Thank you for signing up for Slack. We’re happy you’re here!

Enter the following code in the window where you began creating your new
Slack workspace:

862-655

This email contains private information for your Slack account —
please don’t forward it. Questions about setting up Slack? Email us at
feedback@slack.com.

**Comment by DaveYesland** [comment]
Welcome to Slack!

You’ve created the new Slack workspace github. Here are your account
details:

G

Workspace name: github

URL: github-buf9768.slack.com [https://github-buf9768.slack.com/]

Email: reply@reply.github.com

Your workspace is on the free plan [https://slack.com/pricing], with
unlimited messaging and the ability to search the 10,000 most recent
messages.

Want to learn more now?
[https://get.slack.help/hc/en-us/categories/202622877-slack-guides?cvosrc=email.email.email_ntws&cvo_creative=&utm_medium=email&utm_source=email&utm_campaign=_email_email____ob-_cr-_ym-]

Check out our Slack guides
[https://get.slack.help/hc/en-us/categories/202622877-slack-guides?cvosrc=email.email.email_ntws&cvo_creative=&utm_medium=email&utm_source=email&utm_campaign=_email_email____ob-_cr-_ym-]
for tips on messaging with your team, sharing files, and getting updates
from your other tools.

**Comment by DaveYesland** [comment]
reply_aj73oa7z2hdaibr, forward this email to the people you’d like to
invite to your workspace. Anyone who has this message can use the link
below to sign up. Manage your invite link
[https://github-buf9768.slack.com/admin/shared_invites]

Join github on Slack

reply_aj73oa7z2hdaibr has created the new Slack workspace github. You
can use the link below to join this workspace — it only takes a minute
to create an account!

Use this link to get started:

https://join.slack.com/t/github-buf9768/shared_invite/enQtNjA3NDAyMDA3ODQxLWU1MDYxMjQ0NmZlZDQxYmI3MWZjNWI3Yzc2NWI0MjlkNDRjOTEzNDdiY2YwN2JjMmZkMzI2N2U2ODk4YzYzMTc
What is Slack? [https://slack.com/is]

Slack makes it easy for teams to communicate and get work done together.
See Slack in action. [https://slack.com/is]

https://slack.com/is

**Comment by DaveYesland** [comment]
Hi reply_aj73oa7z2hdaibr,

We received an attempt to create an account for
reply@reply.github.com on
github, but this account already exists.

You can sign in [https://slack.com/signin] to that account, or request a
password change [https://github-buf9768.slack.com/forgot].

If you no longer need help accessing this account, you can ignore this
email.

Workspace name: github
Workspace URL:
Email:

**Comment by DaveYesland** [comment]
Reset your password

You told us you forgot your password. Visit the link below to choose a
new one:

https://github-buf9768.slack.com/x-613654187493-613152817476/reset/enQtNjE1NTM4Mzg4ODIzLTk0MzM2ZDIwMjAyNmNjMzdhNzc5NTI2MTgwZjA2YjZhNTlkMzQ5MjJkNmE2MjJjYmM5ZTYyZmIxYzg3MWI3NmE

If you didn’t mean to reset your password, then you can just ignore
this email; your password will not change.

**Comment by DaveYesland** [comment]
You have a new password!

Your password for signing in to github was recently changed. If you made
this change, then we're all set.

If you did not make this change, please reset your password to secure
your account.

https://github-buf9768.slack.com/forgot

Either way, feel free to reach out with any questions you might have.
We're here to help.

Best,
The team at Slack

**Comment by DaveYesland** [comment]
@DaveYesland

**Comment by d-l-y** [comment]
@daveyesland
